### ISSUE TITLE
Image scaling

### ISSUE THREAD

**Issue by mozharovsky** [Athlee/ImageEditorKit#7]
There are some issues with image scaling. Sometimes image doesn't fill all the space, especially when being rotated. It should be intuitive and smooth. 

## Approach 

`CropView` should be resized appropriately to the image provided, thus given it an image NxK, the `cropView.bounds.size` is exactly NxK. This behavior is not the same as in the `ImagePickerKit` – there we only get an image and `Cropable` conformable object must use the provided size as a default one for both `cropView` and image. 

Following this way, we'll get rid of any scaling issues happening while rotating the image. 

## Tasks 

- [ ] Extend `Cropable` protocol to support described behavior 
- [ ] Update the Demo project 
- [ ] Update the Pod
