### ISSUE TITLE
Filtering performance

### ISSUE THREAD

**Issue by mozharovsky** [Athlee/ImageEditorKit#8]
Filtering operations are being performed very slow. This is a huge problem for general app performance. 

## Approach 

Wrappers around `CIFilter` hierarchy are nice. But the `Processor` is not well optimized which makes processing a set of images kinda problematic and time consuming. This, basically, is happening because of using a default `CIContext` which mainly uses the CPU. Instead we'd rather use a context using GPU for the same purpose. 

## Tasks 

- [ ] Optimize `Processor` implementation
- [ ] Use GPU for processing operations (also see #1)
- [ ] Update the Demo project 
- [ ] Update the Pod
